### ISSUE TITLE
arn pattern arn:aws:*:*:*:*/* is failing 

### ISSUE THREAD

**Issue by polasekr** [scopely-devops/skew#103]
I have a following simple code:
`
#!/usr/bin/python

import skew

arn = skew.scan('arn:aws:*:*:*:*/*')
for resource in arn:
      print(resource)
`
When I run it I get following error:

> arn:aws:apigateway:us-east-1:725326807264:restapis/zmgw9h76u7
Traceback (most recent call last):
  File "./scan_failing.py", line 6, in <module>
    for resource in arn:
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 319, in __iter__
    for scheme in self.scheme.enumerate(context, **self.kwargs):
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 244, in enumerate
    context, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 229, in enumerate
    context, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 214, in enumerate
    context, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 195, in enumerate
    context, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 146, in enumerate
    context, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/skew/arn/__init__.py", line 128, in enumerate
    self._arn, region, account, resource_id, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/skew/resources/resource.py", line 28, in enumerate
    cls.Meta.service, region, account, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/skew/awsclient.py", line 139, in get_awsclient
    return AWSClient(service_name, region_name, account_id, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/skew/awsclient.py", line 51, in __init__
    self._client = self._create_client()
  File "/usr/local/lib/python2.7/dist-packages/skew/awsclient.py", line 81, in _create_client
    return session.client(self.service_name, region_name=self.region_name)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 250, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 809, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 62, in create_client
    verify, credentials, scoped_config, client_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 188, in _get_client_args
    timeout=(new_config.connect_timeout, new_config.read_timeout))
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 240, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://iam..amazonaws.com

I am not sure whether it is a bug, or it is illegal pattern. Please can somebody advice?

**Comment by avram** [comment]
Fixed in #104
